window.HAPPINESS_TRIPS = [
  {
    id: 'meghalaya-monsoon',
    title: 'Meghalaya Monsoon Trek & Waterfalls',
    aliases: ['Meghalaya Monsoon Trek & Waterfalls'],
    location: 'Shillong & Cherrapunji',
    image: 'images/image-3398b60.jpg',
    price: 18499,
    dates: 'May 2–7',
    duration: '6D / 5N',
    seatsLeft: 12,
    payAtPickupAllowed: true,
    rating: '4.9',
    tag: 'Adventure'
  },
  {
    id: 'spiti-stargazing',
    title: 'Spiti Valley: High Altitude Stargazing & Monastery Circuit',
    aliases: ['Spiti Valley Stargazing & Homestays', 'Spiti Valley: High Altitude Stargazing'],
    location: 'Kaza, Spiti, Himachal Pradesh',
    image: 'images/image-6fb112d.jpg',
    price: 24999,
    dates: 'May 18–24',
    duration: '7D / 6N',
    seatsLeft: 4,
    payAtPickupAllowed: true,
    rating: '4.96',
    tag: 'Adventure'
  },
  {
    id: 'gokarna-acoustic',
    title: 'Gokarna Cliffside Sunset & Acoustic Jam',
    aliases: ['Gokarna & Murudeshwar'],
    location: 'Gokarna & Murudeshwar',
    image: 'images/image-2865119.jpg',
    price: 11200,
    dates: 'May 10–12',
    duration: '4D / 3N',
    seatsLeft: 8,
    payAtPickupAllowed: true,
    rating: '4.8',
    tag: 'Beach & Chill'
  },
  {
    id: 'kerala-backwaters',
    title: 'Kerala Backwaters & Rainforest Trek',
    aliases: [],
    location: 'Wayanad & Alleppey',
    image: 'images/image-f827caa.jpg',
    price: 12499,
    dates: 'April 24–27',
    duration: '4D / 3N',
    seatsLeft: 6,
    payAtPickupAllowed: true,
    rating: '4.9',
    tag: 'Heritage & Nature'
  },
  {
    id: 'meghalaya-roots',
    title: 'Meghalaya: Living Root Bridges & Caving',
    aliases: [],
    location: 'Cherrapunji & Shnongpdeng',
    image: 'images/image-840f3eb.jpg',
    price: 21999,
    dates: 'May 2–7',
    duration: '6D / 5N',
    seatsLeft: 3,
    payAtPickupAllowed: true,
    rating: '4.95',
    tag: 'Adventure'
  },
  {
    id: 'gokarna-beach-camp',
    title: 'Gokarna & Murudeshwar Beach Camp',
    aliases: ['Gokarna & Murudeshwar Beach Camp'],
    location: 'Gokarna Cliff Trail',
    image: 'images/image-7982c16.jpg',
    price: 7999,
    dates: 'May 10–12',
    duration: '3D / 2N',
    seatsLeft: 8,
    payAtPickupAllowed: true,
    rating: '4.82',
    tag: 'Beach & Chill'
  },
  {
    id: 'jaisalmer-dunes',
    title: 'Jaisalmer Dune Camping & Stargazing',
    aliases: [],
    location: 'Thar Desert & Fort',
    image: 'images/image-1cb936b.jpg',
    price: 14800,
    dates: 'Autumn Departure',
    duration: '4D / 3N',
    seatsLeft: 5,
    payAtPickupAllowed: true,
    rating: '4.88',
    tag: 'Oct Season Special'
  }
];